[project]
name = "simplegif"
version = "1.2.2"
description = ""
authors = [{ name = "jefferson-norberto2", email = "jmn@cin.ufpe.br" }]
license = { text = "Apache-2.0" }
readme = "README.md"
requires-python = "3.12.*"
dependencies = [
    "opencv-python (>=4.12.0.88,<5.0.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "Pillow (>=10.4.0,<11.0.0)",
    "customtkinter (>=5.2.2,<6.0.0)",
    "typeguard (>=4.4.4,<5.0.0)",
    "jinja2 (>=3.1.6,<4.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "pyinstaller (>=6.18.0,<7.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
